[package]
name = "rushtrader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4" }
chrono-tz = { version = "0.6" }
ta-lib-wrapper = { version = "0.2" }